apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k3s-manifests/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-service
  name: cast_service
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 8000
  selector:
    io.kompose.service: cast-service
status:
  loadBalancer: {}
