apiVersion: v1
kind: Service
metadata:
  name: movie-db
  labels:
    app: movie-db
spec:
  type: ClusterIP
  selector:
    io.kompose.service: movie-db
  ports:
    - port: 5432
      targetPort: 5432