apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o k3s-manifests/
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
